[package]
name = "bookfile"
version = "0.1.0"
authors = ["Eric Seppanen <eds@reric.net>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
versioned = { path="../versioned/versioned" }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
byteorder = "1.4"
